-- Large test dataset with 100+ realistic customer support tickets
-- This data will be loaded automatically when the application starts

-- Billing Issues (30 tickets)
INSERT INTO tickets (subject, description, status, category, priority, sentiment, created_at, updated_at) VALUES
('Double charge on my credit card', 'I was charged twice for my subscription this month. Transaction IDs: TXN123 and TXN124. Please refund one of them immediately!', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cannot update payment method', 'The payment page keeps showing an error when I try to update my credit card. Error code: PAY_ERR_500', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Subscription cancelled but still charged', 'I cancelled my subscription last week but was still charged today. This is unacceptable!', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Invoice not received', 'I need my invoice for last month for tax purposes. Can you send it to my email?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refund request for unused service', 'I only used the service for 2 days but was charged for the full month. Can I get a prorated refund?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Wrong currency charged', 'I was charged in USD instead of EUR. The exchange rate made it much more expensive!', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Payment declined but account locked', 'My payment was declined due to insufficient funds, but now my account is locked. How do I fix this?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Upgrade billing issue', 'I upgraded to premium but was charged for both basic and premium plans this month', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tax calculation seems wrong', 'The tax amount on my invoice looks incorrect. Can someone review it?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Auto-renewal charged unexpectedly', 'I did not expect auto-renewal and was charged without warning. Please refund.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Discount code not applied', 'I used promo code SAVE20 but the discount was not applied to my invoice', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Billing address cannot be changed', 'I moved to a new address but cannot update my billing information in the system', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Charged for cancelled trial', 'I cancelled during the trial period but was still charged for the first month', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Multiple subscriptions charged', 'I have two subscriptions showing up on my account but I only signed up for one', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Payment method expired notification', 'My credit card is expiring soon. How do I update it before the next billing cycle?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Overcharged for data usage', 'My bill shows 50GB of data usage but I only used about 20GB according to my records', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Corporate billing setup', 'We need to set up corporate billing for our team of 25 users. What are the steps?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Failed payment retry', 'My payment failed last week. I have updated my card but the system is not retrying the charge', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Billing cycle change request', 'Can I change my billing cycle from monthly to annual to get the discount?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Duplicate invoice received', 'I received two invoices for the same month with different amounts. Which one is correct?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Credit balance not applied', 'I have $50 credit on my account but it was not applied to this month''s invoice', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('International payment issues', 'I am trying to pay from India but the payment keeps failing. Do you accept international cards?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Subscription downgrade refund', 'I downgraded from premium to basic mid-month. Will I get a prorated refund?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('VAT number not on invoice', 'My company VAT number is not showing on the invoice. I need this for accounting.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Payment confirmation not received', 'I made a payment 3 days ago but have not received any confirmation email', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Billing history missing', 'I cannot see my billing history for the past 6 months in my account dashboard', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Unauthorized charge investigation', 'There is a charge on my card that I do not recognize. Please investigate immediately!', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Student discount not working', 'I verified my student email but the discount is not showing on checkout', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Payment plan options', 'Can I split my annual payment into quarterly installments?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Receipt for expense report', 'I need an official receipt for my company expense report. The invoice is not sufficient.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Technical Support (30 tickets)
INSERT INTO tickets (subject, description, status, category, priority, sentiment, created_at, updated_at) VALUES
('Cannot login to my account', 'I keep getting "Invalid credentials" error even though I am using the correct password', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('App crashes on startup', 'The mobile app crashes immediately after I open it. I am using iPhone 14 with iOS 17.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Slow performance issues', 'The dashboard is taking 30+ seconds to load. This started happening yesterday.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Password reset not working', 'I clicked "Forgot Password" but never received the reset email. Checked spam folder too.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('File upload failing', 'I am trying to upload a 50MB PDF but it keeps failing at 90%. Error: Upload timeout', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Two-factor authentication issues', 'I lost my phone and cannot access 2FA codes. How do I regain access to my account?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('API integration not working', 'The API endpoint /v1/users is returning 500 errors since this morning', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Email notifications not received', 'I am not receiving any email notifications even though they are enabled in settings', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Data export stuck', 'I requested a data export 2 days ago but it is still showing "Processing"', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Search function not working', 'The search bar returns no results even for items I can see on the page', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mobile app sync issues', 'Changes I make on mobile are not syncing to the web version', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Browser compatibility problem', 'The site does not work properly in Safari. Buttons are not clickable.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Account locked after failed logins', 'My account was locked after 3 failed login attempts. How long until it unlocks?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Webhook not triggering', 'I set up a webhook for new orders but it is not being triggered', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dark mode not saving', 'I enable dark mode but it resets to light mode every time I log back in', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Integration with Slack failing', 'The Slack integration was working fine but stopped sending notifications yesterday', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cannot delete account', 'I want to delete my account but the delete button is grayed out', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Profile picture not uploading', 'When I try to upload a profile picture, it says "Invalid file format" but it is a JPG', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Timezone settings incorrect', 'All timestamps are showing in UTC instead of my local timezone (PST)', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CSV import errors', 'I am trying to import a CSV file but getting "Invalid format" errors on valid data', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Session timeout too short', 'I keep getting logged out every 5 minutes. Can the session timeout be extended?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Keyboard shortcuts not working', 'None of the keyboard shortcuts work on Windows. They work fine on Mac.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Video playback issues', 'Videos in the training section buffer constantly even with fast internet', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Calendar sync with Google', 'I connected my Google Calendar but events are not syncing properly', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Print function broken', 'When I try to print reports, the layout is completely broken', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Language settings not applying', 'I changed the language to Spanish but most of the interface is still in English', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Notification sound too loud', 'Is there a way to adjust the notification sound volume? It is very loud.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Offline mode not working', 'The app says it has offline mode but nothing works without internet', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Copy-paste not working', 'I cannot copy and paste text in the editor. Ctrl+C and Ctrl+V do nothing.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Auto-save feature missing', 'I lost 2 hours of work because there is no auto-save. Please add this feature!', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Bug Reports (25 tickets)
INSERT INTO tickets (subject, description, status, category, priority, sentiment, created_at, updated_at) VALUES
('Calculation error in reports', 'The total revenue in the monthly report is incorrect. It is showing $10,000 but should be $12,500', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Duplicate entries in database', 'I am seeing duplicate records when I export data. Each entry appears twice.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Button does nothing when clicked', 'The "Save Changes" button on the settings page does not do anything when clicked', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Incorrect date formatting', 'Dates are showing in MM/DD/YYYY format but I set it to DD/MM/YYYY in preferences', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Memory leak in desktop app', 'The desktop app memory usage keeps growing until it crashes. Happens after 2-3 hours.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Broken link in email', 'The verification link in the welcome email leads to a 404 page', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Filter not working correctly', 'When I filter by "Last 7 days" it shows data from last month too', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Chart displaying wrong data', 'The pie chart percentages do not add up to 100%. Shows 87% total.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Infinite loading spinner', 'The page shows a loading spinner forever and never loads the content', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Text overlapping in mobile view', 'On mobile, the text overlaps with the sidebar making it unreadable', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sorting not working', 'Clicking the column headers to sort does nothing. The data stays in the same order.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Form validation error', 'The form says "Email is required" even after I enter a valid email address', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pagination broken', 'Clicking "Next Page" shows the same results as page 1', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dropdown menu cut off', 'The dropdown menu is cut off at the bottom of the screen. Cannot see all options.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Incorrect currency conversion', 'The currency converter is showing 1 USD = 0.85 EUR but the actual rate is 0.92', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Missing translations', 'Several buttons and labels are not translated in the French version', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Autocomplete suggesting wrong items', 'The search autocomplete suggests items that do not match what I am typing', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Image thumbnails not loading', 'All image thumbnails show as broken image icons', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Notification count incorrect', 'The notification badge shows 5 but I only have 2 unread notifications', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Drag and drop not working', 'I cannot reorder items using drag and drop. Nothing happens when I try.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Modal dialog cannot be closed', 'The X button on the popup modal does not close it. I have to refresh the page.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Progress bar stuck at 99%', 'File upload progress bar gets stuck at 99% even though the file uploaded successfully', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Wrong user avatar displayed', 'My profile is showing someone else''s avatar. This is a privacy concern!', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Checkbox state not saving', 'I check the "Remember me" box but it is unchecked when I come back', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Error message in wrong language', 'Error messages appear in German even though my language is set to English', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Feature Requests (15 tickets)
INSERT INTO tickets (subject, description, status, category, priority, sentiment, created_at, updated_at) VALUES
('Add dark mode support', 'Please add a dark mode option. The bright white interface hurts my eyes at night.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bulk edit functionality', 'It would be great to edit multiple items at once instead of one by one', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Export to Excel format', 'Currently only CSV export is available. Please add Excel (.xlsx) export option.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Custom dashboard widgets', 'Allow users to customize their dashboard with widgets they actually need', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mobile app for Android', 'You have an iOS app but no Android app. Please develop one!', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Advanced search filters', 'The current search is too basic. Need filters for date range, category, status, etc.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Team collaboration features', 'Add features like comments, mentions, and shared workspaces for teams', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Scheduled reports', 'Would love to schedule reports to be emailed automatically every week', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Integration with Zapier', 'Please add Zapier integration so we can connect with other tools', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Custom branding options', 'For enterprise users, allow custom logos and color schemes', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Undo/Redo functionality', 'Need undo and redo buttons for when I make mistakes', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Voice commands support', 'Add voice command support for hands-free operation', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Template library', 'Provide pre-built templates that users can customize instead of starting from scratch', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Activity log/audit trail', 'Need to see who made what changes and when for compliance purposes', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Keyboard shortcuts customization', 'Let users customize keyboard shortcuts to match their workflow', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- General Inquiries (10 tickets)
INSERT INTO tickets (subject, description, status, category, priority, sentiment, created_at, updated_at) VALUES
('How do I change my email?', 'I want to update my email address. Where is this option in settings?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('What is the data retention policy?', 'How long do you keep user data after account deletion?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Is there a student discount?', 'I am a university student. Do you offer any educational discounts?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('API rate limits question', 'What are the API rate limits for the premium plan?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Training resources available?', 'Are there any video tutorials or documentation for new users?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Enterprise plan details', 'Can you send me information about enterprise pricing and features?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GDPR compliance question', 'Is your service GDPR compliant? I need this for our legal team.', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Difference between plans', 'What is the difference between the Pro and Premium plans?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Referral program details', 'Do you have a referral program? How does it work?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Data migration assistance', 'I am switching from a competitor. Can you help migrate my data?', 'PENDING', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
